# Generated by Django 5.2.2 on 2025-06-24 22:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_type', models.CharField(max_length=200)),
                ('workout_date', models.DateTimeField(verbose_name='Date of workout')),
                ('notes', models.TextField(blank=True, help_text='Additional workout notes')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_exercise', models.CharField(max_length=200)),
                ('no_of_reps', models.SmallIntegerField()),
                ('no_of_sets', models.SmallIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, help_text='Use KG', max_digits=5)),
                ('rpe_value', models.PositiveIntegerField(blank=True, help_text='Rate of Perceived Exertion (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='tracker.workout')),
            ],
        ),
    ]
