# Generated by Django 5.2.2 on 2025-08-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='workout',
        ),
        migrations.AddField(
            model_name='exercise',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional workout notes'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout_date',
            field=models.DateTimeField(default=None, verbose_name='Date of workout'),
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
