# Generated by Django 5.2.2 on 2025-08-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_exercise_workout_exercise_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name_of_exercise',
            field=models.CharField(choices=[('squat', 'Squat'), ('deadlift', 'Deadlift'), ('rdl', 'Romanian Deadlift (RDL)'), ('benchpress', 'Bench Press'), ('inclinebenchpress', 'Incline Bench Press'), ('dumbellpress', 'Dumbell Press'), ('inclinedumbellpress', 'Incline Dumbell Press'), ('pullup', 'Pull Up'), ('overheadpress', 'Overhead Press'), ('lunge', 'Lunge'), ('bicepcurl', 'Bicep Curl'), ('tricepdip', 'Tricep Dip'), ('triceppushdown', 'Tricep Pushdown'), ('skullcrusher', 'Skull Crusher'), ('legpress', 'Leg Press'), ('lateralraise', 'Lateral Raise'), ('latpulldown', 'Lat Pulldown'), ('legcurl', 'Leg Curl'), ('calfraise', 'Calf Raise'), ('legextension', 'Leg Extension'), ('stepup', 'Step Ups'), ('hipabduction', 'Hip Abduction'), ('kickbacks', 'Kickbacks'), ('seatedrow', 'Seated Row'), ('hipthrust', 'Hip Thrust'), ('pecfly', 'Pec Fly'), ('dumbellshoulderpress', 'Dumbell Shoulder Press'), ('facepull', 'Face Pull')], max_length=200),
        ),
    ]
