# Generated by Django 5.2.2 on 2025-08-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_exercise_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='author',
        ),
    ]
